### ISSUE TITLE
codeclimate removed `engines:enable` command already

### ISSUE THREAD

**Issue by kitoneat** [wrike/codeclimate-dart#1]
How can I install it to latest version codeclimate?
thanks

**Comment by zgosalvez** [comment]
`engines` was changed to `plugins`. However, adding this doesn't work.
```yaml
plugins:
  dart:
    enabled: true
```
I keep getting `WARNING: unknown engine <dart:stable>`
